export const GET_POKEMONS = 'GET_POKEMONS';
export const GET_POKEMONS_DETAILS = 'GET_POKEMONS_DETAILS';
export const CLEAR_DETAILS = 'CLEAR_DETAILS';
export const POST_POKEMON = 'POST_POKEMON';
export const GET_TYPES = 'GET_TYPES';